
2. Erstellen Sie einen Workflow in Ihrer GitHub-Repository-Datei (z.B. ".github/workflows/render.yml") mit dem folgenden Inhalt:

```yaml
name: Render Flexdashboard

on:
  push:
    paths:
      - my-dashboard.Rmd

jobs:
  render:
    name: Render my-dashboard.Rmd
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v2
      - uses: r-lib/actions/setup-pandoc@v2
      - uses: r-lib/actions/setup-tinytex@v2
      - name: Install required packages
        run: |
          Rscript -e 'install.packages(c("flexdashboard", "ggplot2"))'
      - name: Render my-dashboard.Rmd
        run: Rscript -e 'rmarkdown::render("my-dashboard.Rmd")'
      - name: Commit and push changes
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add my-dashboard.html
          git commit -m 'Re-render my-dashboard.Rmd'
          git push
