---
title: "V2"
output: 
  github_document: default
  word_document: default
  flexdashboard::flex_dashboard: 
    orientation: rows
    vertical_layout: fill
  pdf_document: default
---
Row
-----------------------------------------------------------------------

### Grafik 1

```{r Einbuergungen-Grafik-1, echo=FALSE, fig.cap="Anzahl der monatlichen Einbuergerungen in Niedersachsen"}
library("ggplot2")

# Laden Sie die CSV-Datei aus dem Ordner "data" im Repository
data <- read.csv("../data/2022_Einbuergerung.csv", sep = ";")

# Die Monate in der richtigen Reihenfolge als Faktor erstellen
data$Monat <- factor(data$Monat, levels = c("Januar", "Februar", "Maerz", "April", "Mai", "Juni", "Juli", "August", "September", "Oktober", "November", "Dezember"))

# Daten für die Berechnung der Differenzen vorbereiten
data$Diff <- c(NA, diff(data$Einbuergerungen))

# Die Grafik anzeigen
print(ggplot(data, aes(x = Monat, y = Einbuergerungen)) +
  geom_point() +  # Datenpunkte hinzufügen
  geom_text(aes(label = round(Einbuergerungen)), 
            vjust = ifelse(data$Diff < 0, 1.5, -0.5 + ifelse(data$Einbuergerungen < 500, 0.4, ifelse(data$Monat == "Januar", 2.2, 0)))) +
  labs(title = "Anzahl der monatlichen Einbürgerungen in Niedersachsen", x = "Monat", y = "Einbuergerungen") +
  theme_minimal() +  # Hintergrund weiß machen
  scale_x_discrete(guide = guide_axis(n.dodge = 2))  # Achsenabschnitte breiter machen
)


#ggplot(data, aes(x = Monat, y = Einbuergerungen)) +
#  geom_point() +  # Datenpunkte hinzufügen
#  geom_text(aes(label = round(Einbuergerungen)), 
#            vjust = ifelse(data$Diff < 0, 1.5, -0.5 + ifelse(data$Einbuergerungen < 500, 0.4, ifelse(data$Monat == "Januar", 2.2, 0)))) +
#  labs(title = "Anzahl der monatlichen Einbürgerungen in Niedersachsen", x = "Monat", y = "Einbuergerungen") +
#  theme_minimal() +  # Hintergrund weiß machen
#  scale_x_discrete(guide = guide_axis(n.dodge = 2))  # Achsenabschnitte breiter machen


```

### Grafik 2

```{r load-bst-daten-2, echo = FALSE, message=FALSE}

library(readxl)
library(tidyverse)

# Pfad zur Excel-Datei im "data" -Ordner
excel_path <- "../data/bst_hochrechnung.xlsx"

# Tabellenblattname
sheet_name <- "Zeitreihe Beschäftigte"

# Daten einlesen aus den angegebenen Spalten
bst_daten <- read_excel(excel_path, sheet = sheet_name, range = "A160:G173", col_names = FALSE) %>%
  select(...1, ...2, ...7)  # Nur die gewünschten Spalten auswählen

# Spaltenüberschriften setzen
col_names <- c("Zeit", "Deutschland", "Niedersachsen")
colnames(bst_daten) <- col_names
```
```{r Beschaeftigte-Grafik-1, echo=FALSE, message=FALSE}
library(ggplot2)

# Liniendiagramm erstellen
ggplot(bst_daten, aes(x = Zeit)) +
  geom_line(aes(y = Deutschland, color = "Deutschland"), show.legend = FALSE) +
  geom_point(aes(y = Deutschland, color = "Deutschland"), show.legend = FALSE) +
  geom_line(aes(y = Niedersachsen, color = "Niedersachsen"), show.legend = FALSE) +
  geom_point(aes(y = Niedersachsen, color = "Niedersachsen"), show.legend = FALSE) +
  labs(title = "Beschäftigungsentwicklung in Deutschland und Niedersachsen",
       x = "Zeit", y = "Beschäftigte",
       caption = "Sozialversicherungspflichtig und ausschließlich geringfügig Beschäftigte") +
  scale_color_manual(values = c("Deutschland" = "blue", "Niedersachsen" = "red")) +
  theme_minimal() +
  scale_y_continuous(labels = function(x) format(x, big.mark = ".", decimal.mark = ",", scientific = FALSE), limits = c(0, NA))

```

### Grafik 3

```{r Grafik3}
# Daten erstellen
data <- data.frame(x = 1:5, y = c(2, 4, 1, 6, 3))

# Plot erstellen
library(ggplot2)
plot <- ggplot(data, aes(x, y)) +
  geom_point() +
  labs(title = "Einfaches Beispielgrafik", x = "X-Achse", y = "Y-Achse")

# Die Grafik anzeigen
print(plot)

```

Row
-----------------------------------------------------------------------

### Grafik 4

```{r}
# R-Chunk für Grafik 4
```

### Grafik 5

```{r}
# R-Chunk für Grafik 5
```

### Grafik 6

```{r}
# R-Chunk für Grafik 6
```


# Einführung mit Grafik
---

Word, Pdf, html, tex. Ich bin ja mal gespannt.



# Einbuergerungen in Niedersachsen
---

Die folgende Grafik zeigt die Entwicklung der Einbuergerungen in Niedersachsen in den vergangenen 12 Monaten.

```{r Einbuergungen_Grafik, echo=FALSE, fig.cap="Anzahl der monatlichen Einbuergerungen in Niedersachsen"}
library("ggplot2")

# Laden Sie die CSV-Datei aus dem Ordner "data" im Repository
data <- read.csv("../data/2022_Einbuergerung.csv", sep = ";")

# Die Monate in der richtigen Reihenfolge als Faktor erstellen
data$Monat <- factor(data$Monat, levels = c("Januar", "Februar", "Maerz", "April", "Mai", "Juni", "Juli", "August", "September", "Oktober", "November", "Dezember"))

# Daten für die Berechnung der Differenzen vorbereiten
data$Diff <- c(NA, diff(data$Einbuergerungen))

ggplot(data, aes(x = Monat, y = Einbuergerungen)) +
  geom_point() +  # Datenpunkte hinzufügen
  geom_text(aes(label = round(Einbuergerungen)), 
            vjust = ifelse(data$Diff < 0, 1.5, -0.5 + ifelse(data$Einbuergerungen < 500, 0.4, ifelse(data$Monat == "Januar", 2.2, 0)))) +
  labs(title = "Anzahl der monatlichen Einbürgerungen in Niedersachsen", x = "Monat", y = "Einbuergerungen") +
  theme_minimal() +  # Hintergrund weiß machen
  scale_x_discrete(guide = guide_axis(n.dodge = 2))  # Achsenabschnitte breiter machen


```
```{r load_bst_daten_1, echo = FALSE, message=FALSE}

library(readxl)
library(tidyverse)

# Pfad zur Excel-Datei im "data" -Ordner
excel_path <- "../data/bst_hochrechnung.xlsx"

# Tabellenblattname
sheet_name <- "Zeitreihe Beschäftigte"

# Daten einlesen aus den angegebenen Spalten
bst_daten <- read_excel(excel_path, sheet = sheet_name, range = "A160:G173", col_names = FALSE) %>%
  select(...1, ...2, ...7)  # Nur die gewünschten Spalten auswählen

# Spaltenüberschriften setzen
col_names <- c("Zeit", "Deutschland", "Niedersachsen")
colnames(bst_daten) <- col_names
```

## Beschäftigte
---
```{r load_bst_daten, echo = FALSE, message=FALSE}

library(readxl)
library(tidyverse)

# Pfad zur Excel-Datei im "data" -Ordner
excel_path <- "../data/bst_hochrechnung.xlsx"

# Tabellenblattname
sheet_name <- "Zeitreihe Beschäftigte"

# Daten einlesen aus den angegebenen Spalten
bst_daten <- read_excel(excel_path, sheet = sheet_name, range = "A160:G173", col_names = FALSE) %>%
  select(...1, ...2, ...7)  # Nur die gewünschten Spalten auswählen

# Spaltenüberschriften setzen
col_names <- c("Zeit", "Deutschland", "Niedersachsen")
colnames(bst_daten) <- col_names
```
```{r Beschaeftigte_Grafik, echo=FALSE, message=FALSE}
library(ggplot2)

# Liniendiagramm erstellen
ggplot(bst_daten, aes(x = Zeit)) +
  geom_line(aes(y = Deutschland, color = "Deutschland"), show.legend = FALSE) +
  geom_point(aes(y = Deutschland, color = "Deutschland"), show.legend = FALSE) +
  geom_line(aes(y = Niedersachsen, color = "Niedersachsen"), show.legend = FALSE) +
  geom_point(aes(y = Niedersachsen, color = "Niedersachsen"), show.legend = FALSE) +
  labs(title = "Beschäftigungsentwicklung in Deutschland und Niedersachsen",
       x = "Zeit", y = "Beschäftigte",
       caption = "Sozialversicherungspflichtig und ausschließlich geringfügig Beschäftigte") +
  scale_color_manual(values = c("Deutschland" = "blue", "Niedersachsen" = "red")) +
  theme_minimal() +
  scale_y_continuous(labels = function(x) format(x, big.mark = ".", decimal.mark = ",", scientific = FALSE), limits = c(0, NA))

```

