---
title: "MDE"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
runtime: shiny
header-includes:
  - <script src="popup.js"></script>
---


```{r setup, include=FALSE}
library(flexdashboard)
library(ggplot2)
```

```javascript
$(document).ready(function() {
  // Binden Sie die Klickfunktion an die Grafiken
  $("#Einbuergungen-Grafik-1 .thumbnail").click(function() {
    var imgSrc = $("#Einbuergungen-Grafik-1 img").attr("src");
    showModalDialog(imgSrc, "Grafik 1");
  });

  // Fügen Sie ähnliche Funktionen für die anderen Grafiken hinzu, falls erforderlich
});
```

Row
-----------------------------------------------------------------------

### Einbürgerungen nach Niedersachsen
```{r popup}
output$Einbuergungen_Grafik_1 <- renderPrint({
  showModal(modalDialog(
    plotOutput("plot1", click = "plot1_click"),
    title = "Grafik 1"
  ))
})

plotOutput("plot1")

```

```{r Einbuergungen-Grafik-1, echo=FALSE, fig.cap="Anzahl der monatlichen Einbuergerungen in Niedersachsen"}
library("ggplot2")

# Laden Sie die CSV-Datei aus dem Ordner "data" im Repository
data <- read.csv("../data/2022_Einbuergerung.csv", sep = ";")

# Die Monate in der richtigen Reihenfolge als Faktor erstellen
data$Monat <- factor(data$Monat, levels = c("Januar", "Februar", "Maerz", "April", "Mai", "Juni", "Juli", "August", "September", "Oktober", "November", "Dezember"))

# Daten für die Berechnung der Differenzen vorbereiten
data$Diff <- c(NA, diff(data$Einbuergerungen))

# Die Grafik anzeigen
ggplot(data, aes(x = Monat, y = Einbuergerungen)) +
  geom_point() +  # Datenpunkte hinzufügen
  geom_text(aes(label = round(Einbuergerungen)), 
            vjust = ifelse(data$Diff < 0, 1.5, -0.5 + ifelse(data$Einbuergerungen < 500, 0.4, ifelse(data$Monat == "Januar", 2.2, 0)))) +
  labs(title = "Anzahl der monatlichen Einbürgerungen in Niedersachsen", x = "Monat", y = "Einbuergerungen") +
  theme_minimal() +  # Hintergrund weiß machen
  scale_x_discrete(guide = guide_axis(n.dodge = 2))  # Achsenabschnitte breiter machen


```



### Beschäftigte

```{r load-bst-daten-2, echo = FALSE, message=FALSE}

library(readxl)
library(tidyverse)

# Pfad zur Excel-Datei im "data" -Ordner
excel_path <- "../data/bst_hochrechnung.xlsx"

# Tabellenblattname
sheet_name <- "Zeitreihe Beschäftigte"

# Daten einlesen aus den angegebenen Spalten
bst_daten <- read_excel(excel_path, sheet = sheet_name, range = "A160:G173", col_names = FALSE) %>%
  select(...1, ...2, ...7)  # Nur die gewünschten Spalten auswählen

# Spaltenüberschriften setzen
col_names <- c("Zeit", "Deutschland", "Niedersachsen")
colnames(bst_daten) <- col_names
```
```{r Beschaeftigte-Grafik-1, echo=FALSE, message=FALSE}
library(ggplot2)

# Liniendiagramm erstellen
ggplot(bst_daten, aes(x = Zeit)) +
  geom_line(aes(y = Deutschland, color = "Deutschland"), show.legend = FALSE) +
  geom_point(aes(y = Deutschland, color = "Deutschland"), show.legend = FALSE) +
  geom_line(aes(y = Niedersachsen, color = "Niedersachsen"), show.legend = FALSE) +
  geom_point(aes(y = Niedersachsen, color = "Niedersachsen"), show.legend = FALSE) +
  labs(title = "Beschäftigungsentwicklung in Deutschland und Niedersachsen",
       x = "Zeit", y = "Beschäftigte",
       caption = "Sozialversicherungspflichtig und ausschließlich geringfügig Beschäftigte") +
  scale_color_manual(values = c("Deutschland" = "blue", "Niedersachsen" = "red")) +
  theme_minimal() +
  scale_y_continuous(labels = function(x) format(x, big.mark = ".", decimal.mark = ",", scientific = FALSE), limits = c(0, NA))

```



### Hier können Sie R-Code für Grafik 3 hinzufügen

Row
-----------------------------------------------------------------------

### Hier können Sie R-Code für Grafik 4 hinzufügen

### Hier können Sie R-Code für Grafik 5 hinzufügen

### Hier können Sie R-Code für Grafik 6 hinzufügen
