on:
  push:
    paths:
      - docs/my-document.Rmd

name: Render my document

jobs:
  render:
    name: Render my document
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v2
      - uses: r-lib/actions/setup-pandoc@v2
      - uses: r-lib/actions/setup-tinytex@v2
      - name: Install rmarkdown, readxl, and ggplot2
      run: |
        Rscript -e 'install.packages(c("rmarkdown", "readxl", "ggplot2"))'
      - name: Render my document to all types
        run: Rscript -e 'rmarkdown::render("docs/my-document.Rmd", output_format = "all")'
      - name: Commit results
        run: |
          git add docs/my-document*
          git commit -m 'Re-build my-document' || echo "No changes to commit"
          git push origin || echo "No changes to commit"
